version: '3.9'

services:
  # # docker exec k0s cat /var/lib/k0s/pki/admin.conf
  # mcp:
  #   container_name: k0s
  #   image: docker.io/k0sproject/k0s:v1.28.3-k0s.0
  #   command: k0s controller --enable-worker --no-taints
  #   hostname: k0s
  #   privileged: true
  #   volumes:
  #     - mcp-var-lib-k0s:/var/lib/k0s
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   tmpfs:
  #     - /run
  #     - /var/run
  #   ports:
  #     - "6443:6443"
  #   cgroup: host
  #   network_mode: "bridge"
  # magico:
  #   image: mattipaksula/magico:5
  #   build: components/magico
  #   env_file:
  #     - .env.magico
  #   volumes:
  #     - ./components/magico/app:/app
  #     - ./cloudflare/cert.pem:/cert.pem
  #   ports:
  #     - 8080:8080

  # beacon:
  #   build: components/beacon
  #   image: mattipaksula/beacon:latest

  worker:
    build:
      context: components/worker
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}/worker:latest
          - ghcr.io/${GITHUB_REPOSITORY}/worker:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    env_file:
      - .env.worker
    privileged: true
    volumes:
      - /var/lib/k0s
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /var/run
    cgroup: host
    network_mode: "bridge"

volumes:
  mcp-var-lib-k0s:
